config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'categories#index'
  get 'categories/:category_id/tasks/today' => 'tasks#today', as: 'tasks_today'

  resources :categories do
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :details)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :get_category
  # skip_before_action :get_category, only: [:today]

  def index
    @tasks = @category.tasks
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to category_tasks_path
    else
      render :new
    end
  end

  def edit
    @task = @category.tasks.find(params[:id])
  end

  def update
    @task = @category.tasks.find(params[:id])
    @task.update(name: params[:task][:name], details: params[:task][:details])
    redirect_to category_tasks_path
  end

  def show
    @task = @category.tasks.find(params[:id])
  end

  def destroy
    @task = @category.tasks.find(params[:id])
    @task.destroy
    redirect_to category_tasks_path
  end

  def today
    # @tasks = Task.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
    @tasks = @category.tasks.where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)
  end

  private

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:name, :details, :category_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="card">
  <div class="card-header">
    <%= category.id %> | <%= category.name %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= category.details %></h5>
    <p class="card-text">Created: <%= category.created_at %></p>
    <p class="card-text">Updated: <%= category.updated_at %></p>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, for: "exampleFormControlInput1", class: "form-label" %>
    <%= form.text_field :name, class: "form-control", id: "exampleFormControlInput1", placeholder: "Category name" %>
  </div>

  <div class="mb-3">
    <%= form.label :details, for: "exampleFormControlTextarea1", class: "form-label" %>
    <%= form.text_area :details, class: "form-control", id: "exampleFormControlTextarea1", rows: "3", placeholder: "Details of the category" %>
  </div>

  <div class="mb-3">
    <%= form.submit :class => 'btn btn-primary mt-1 mb-3' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="d-flex p-2 justify-content-center align-items-center">
  <h1>Editing category</h1>
</div>
<div class="w-50 mx-auto">
  <%= render "form", category: @category %>
  <%= link_to "Show this category", @category, class:"btn btn-primary mt-1 mb-3", role: "button" %>
  <%= link_to "Back to categories", categories_path, class:"btn btn-primary mt-1 mb-3", role: "button" %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex p-2 justify-content-center align-items-center">
  <h1>Categories</h1>
  <%= link_to "+ New category", new_category_path, class: "btn btn-primary ms-3", role: "button" %>
</div>
<div id="categories" class="w-50 mx-auto">
  <% @categories.each do |category| %>
    <%= render category %>
    <%= link_to "Show this category", category, class:"btn btn-primary mt-1 mb-3", role: "button" %>
    <%= link_to "Show tasks in this category", category_tasks_path(category.id), class:"btn btn-primary mt-1 mb-3", role: "button" %>
  <% end %>
</div>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<div class="w-50 mx-auto">
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category), class:"btn btn-primary mt-1 mb-3", role: "button" %>
  <%= link_to "Back to categories", categories_path, class:"btn btn-primary mt-1 mb-3", role: "button" %>
  <%= link_to "Show tasks", category_tasks_path(@category), class:"btn btn-primary mt-1 mb-3", role: "button" %>
  <%= button_to "Destroy this category", @category, method: :delete, class:"btn btn-danger mt-1 mb-3", form: {style: 'display:inline-block;'} %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalAppRailsScaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- CSS only -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid">
      <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
          <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
          <span class="fs-4">Journal App</span>
        </a>

        <ul class="nav nav-pills">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Categories", root_path, {class: "nav-link"} %>
            </li>
            <li class="nav-item">
              <%= link_to "Tasks Today", root_path, {class: "nav-link"} %>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#"><%= current_user.email %> </a>
            </li>
            <li class="nav-item">
              <%= button_to "Log out", destroy_user_session_path, {method: :delete, class: "btn btn-danger"} %>
            </li>
          <% else %>
              <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, {class: "btn btn-outline-primary", role: "button"} %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, {class: "nav-link" , role: "button"} %>
              </li>
          <% end %>
        </ul>
      </header>
    </div>

    <div class="container-fluid">
      <%= yield %>
    </div>
    
    

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/edit.html.erb

<div class="w-50 mx-auto">
<%= form_with model: [@category, @task], scope: :task, url: category_task_path(@category.id), method: :patch, local: true do |f| %>
    
    <% if @task.errors.any? %>
        <div style="color: red">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
            <% @task.errors.each do |error| %>
            <li><%= error.full_message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <%= f.label 'Tasks Title', for: "exampleFormControlInput1", class: "form-label" %>
    <%= f.text_field :name, class: "form-control", id: "exampleFormControlInput1" %>

    <%= f.label 'Category Details', for: "exampleFormControlTextarea1", class: "form-label" %>
    <%= f.text_area :details, class: "form-control", id: "exampleFormControlTextarea1", rows: "3" %>

    <%= f.submit "Edit Task" %>
<% end %>
</div>

app/views/tasks/index.html.erb
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Details</th>
            <th scope="col">Show</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
            <tr scope="row">
                <td><%= task.id %></td>
                <td><%= task.name %></td>
                <td><%= task.details %></td>
                <td><%= link_to 'Details', category_task_path(@category.id, task.id), class: "btn btn-primary", role: "button" %></td>
            </tr>
        <% end %>
    </tbody>
</table>


<%= link_to 'New Task', new_category_task_path(@category), class:"btn btn-primary mt-1 mb-3"%>
<%= link_to 'Show Task today', tasks_today_path(@category), class:"btn btn-primary mt-1 mb-3"%>
<%= link_to "Back to categories", categories_path, class:"btn btn-primary mt-1 mb-3" %> 

app/views/tasks/new.html.erb

<div class="w-50 mx-auto">

<%= form_with model: [@category, @task], local: true do |f| %>
    <p>
        <% if @task.errors.any? %>
            <ul>
                <% @task.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        <% end %>
    </p>

    <p>
        <%= f.label :name, for: "exampleFormControlInput1", class: "form-label" %>
        <%= f.text_field :name, class: "form-control", id: "exampleFormControlInput1" %>
    </p>
    <p>
        <%= f.label :details, for: "exampleFormControlTextarea1", class: "form-label" %>
        <%= f.text_area :details, class: "form-control", id: "exampleFormControlTextarea1", rows: "3" %>
    </p>

    <p>
        <%= f.submit :class => 'btn btn-primary mt-1 mb-3' %>
    </p>
<% end %>
</div>

app/views/tasks/show.html.erb
<div class="w-50 mx-auto">
<p style="color: green"><%= notice %></p>

<div class="card">
    <div class="card-header">
        <%= @task.id %> | <%= @task.name %>
    </div>
    <div class="card-body">
        <h5 class="card-title"><%= @task.role %></h5>
        <p class="card-text"><%= @task.is_approved %></p>
        <p class="card-text"><%= @task.unconfirmed_email %></p>
    </div>
    
</div>
</div>



app/views/tasks/today.html.erb
<table class="table">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Details</th>
            <th scope="col">Show</th>
        </tr>
    </thead>
    <tbody>
        <% @tasks.each do |task| %>
            <tr scope="row">
                <td><%= task.id %></td>
                <td><%= task.name %></td>
                <td><%= task.details %></td>
                <td><%= link_to 'Details', category_task_path(@category, task.id), class: "btn btn-primary", role: "button" %></td>
            </tr>
        <% end %>
    </tbody>
</table>